'use client';

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import pptxgen from "pptxgenjs";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";

/**
 * Utility to download a table-like data structure as an Excel file.
 */
export function downloadTableAsExcel(headers: string[], body: any[][], fileName: string) {
  const ws = XLSX.utils.aoa_to_sheet([headers, ...body]);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
  XLSX.writeFile(wb, `${fileName}.xlsx`);
}

/**
 * Utility to download a table-like data structure as a PDF file.
 */
export function downloadTableAsPDF(title: string, headers: string[], body: any[][], fileName: string) {
  const doc = new jsPDF() as any;
  doc.setFontSize(18);
  doc.text(title, 14, 22);
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Generated by StudySpark - ${new Date().toLocaleDateString()}`, 14, 30);

  doc.autoTable({
    startY: 35,
    head: [headers],
    body: body,
    theme: 'grid',
    headStyles: { fillGray: 200, textColor: 0, fontStyle: 'bold' },
    styles: { overflow: 'linebreak' },
  });

  doc.save(`${fileName}.pdf`);
}

/**
 * Utility to download rich text or structured AI content as a PDF file.
 */
export function downloadTextAsPDF(title: string, content: string, fileName: string, subtitle?: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const maxLineWidth = pageWidth - margin * 2;

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 25);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text(`StudySpark AI Response - ${new Date().toLocaleString()}`, margin, 32);

  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    const splitSubtitle = doc.splitTextToSize(subtitle, maxLineWidth);
    doc.text(splitSubtitle, margin, 42);
  }

  // Content
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0);
  
  const startY = subtitle ? 55 : 45;
  const splitText = doc.splitTextToSize(content, maxLineWidth);
  
  doc.text(splitText, margin, startY);

  doc.save(`${fileName}.pdf`);
}

/**
 * Specifically for Career Navigator or other structured objects
 */
export function downloadObjectAsPDF(title: string, sections: { title: string, content: string | string[] }[], fileName: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const maxLineWidth = pageWidth - margin * 2;

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 25);

  let currentY = 40;

  sections.forEach((section) => {
    // Section Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246); // Primary Blue
    doc.text(section.title.toUpperCase(), margin, currentY);
    currentY += 8;

    // Section Content
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50);

    const contents = Array.isArray(section.content) ? section.content : [section.content];
    contents.forEach((text) => {
      const splitText = doc.splitTextToSize(text, maxLineWidth - 5);
      doc.text(splitText, margin + 2, currentY);
      currentY += (splitText.length * 6) + 4;

      if (currentY > 270) {
        doc.addPage();
        currentY = 20;
      }
    });

    currentY += 10;
  });

  doc.save(`${fileName}.pdf`);
}

/**
 * Utility to download a structured object as a DOCX file.
 */
export async function downloadObjectAsDOCX(title: string, sections: { title: string, content: string | string[] }[], fileName: string) {
  const docElements: any[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by StudySpark AI on ${new Date().toLocaleDateString()}`,
          italics: true,
          color: "666666",
        }),
      ],
      spacing: { after: 600 },
    }),
  ];

  sections.forEach(section => {
    docElements.push(
      new Paragraph({
        text: section.title.toUpperCase(),
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      })
    );

    const contents = Array.isArray(section.content) ? section.content : [section.content];
    contents.forEach(text => {
      docElements.push(
        new Paragraph({
          children: [
            new TextRun({
              text: text,
              size: 24,
            }),
          ],
          spacing: { after: 200 },
        })
      );
    });
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children: docElements,
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${fileName}.docx`);
}

/**
 * Utility to download a presentation structure as a PPTX file.
 */
export function downloadPresentationAsPPTX(title: string, slides: { title: string, content: string[] }[]) {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';

  // Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: 'F1F5F9' }; // primary/5 equivalent
  
  titleSlide.addText(title, { 
    x: 1, y: 1.5, w: 8, h: 2, 
    fontSize: 44, color: '0078d4', 
    bold: true, align: 'center', 
    valign: 'middle' 
  });
  
  titleSlide.addText("Generated by StudySpark AI", { 
    x: 1, y: 3.5, w: 8, h: 1, 
    fontSize: 18, color: '666666', 
    align: 'center' 
  });

  // Content Slides
  slides.forEach(slideData => {
    const slide = pptx.addSlide();
    
    // Slide Title
    slide.addText(slideData.title, { 
      x: 0.5, y: 0.5, w: 9, h: 1, 
      fontSize: 32, color: '0078d4', 
      bold: true 
    });
    
    // Slide Content (Bullets)
    const bullets = slideData.content.map(text => ({ 
      text, 
      options: { bullet: true, indentLevel: 0, margin: [5, 0, 5, 0] } 
    }));
    
    slide.addText(bullets, { 
      x: 0.5, y: 1.5, w: 9, h: 3.5, 
      fontSize: 18, color: '363636', 
      valign: 'top' 
    });
  });

  pptx.writeFile({ fileName: `${title.replace(/\s+/g, '_')}_Presentation.pptx` });
}
