import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import AuthProvider from '@/lib/auth/auth-provider';
import { Toaster } from '@/components/ui/toaster';
import { FirebaseErrorListener } from '@/components/firebase-error-listener';
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'StudySpark - Modern Academic Hub',
  description: 'A refined academic workspace featuring AI tutoring, automated planning, and intelligent productivity tools.',
  keywords: [
    'STUDYSPARK',
    'STUDYSPARK AI',
    'Rishabh',
    'Rishabdev',
    'Rishabdev Tripathi',
    'Students helper',
    'HyperAI',
    'Teacher Friend',
    'Academic Workspace',
    'AI Tutoring',
    'Study Planning',
    'Productivity Tools',
    'Next.js AI App',
    'Modern Learning Hub',
    'online learning platform',
    'academic hub',
    'student learning portal',
    'e-learning website',
    'university study materials',
    'competitive exam preparation',
    'free study notes',
    'exam preparation platform',
    'student knowledge hub', 
    'research-based learning',
    'AI-powered learning',
    'personalized learning platform',
    'adaptive learning system',
    'smart study tools',
    'gamified learning platform',
    'microlearning platform',
    'self-paced online courses',
    'hybrid learning system',
    'AI study assistant',
    'automated exam preparation',
    'ai academic platform',
    'ai learning management system',
    'academic productivity platform',
    'student operating system',
    'academic super app',
    'intelligent learning hub',
    'smart academic ecosystem',
    'digital campus platform',
    'all in one student platform',
    'ai powered education dashboard',
    'global academic platform',
    'cloud based academic platform',
    'international student learning hub',
    'next generation education platform',
    'future ready learning platform',
    'ai tutor online',
    'ai tutor for college students',
    'ai homework helper',
    'ai assignment solver',
    'ai research assistant for students',
    'ai study assistant',
    'ai lesson planner for teachers',
    'ai academic assistant',
    'ai powered tutoring system',
    'personalized learning platform',
    'adaptive learning system',
    'smart study planner app',
    'ai study planner',
    'exam planning dashboard',
    'academic task manager',
    'student productivity app',
'academic performance tracking system',
'student analytics dashboard',
'academic progress tracker',
'study intensity tracker',
'education analytics platform',
'ai ppt generator',
'ai presentation maker for students',
'automatic slide generator',
'ppt generator for teachers',
'ai slide maker',
'educational games platform',
'study break games online',
'brain training games for students',
'gamified learning platform',
'multilingual academic dictionary',
'ai language support for students',
'education super app',
'saas for education platform',
'academic management software',
'ai powered university platform',
'digital education ecosystem',
'modern academic hub',
'advanced academic platform',
'online learning platform worldwide',
'education technology platform',
'edtech innovation platform',
'ai first education platform',
  'ai classroom platform',
'ai powered campus system',
'intelligent academic workspace',
'digital learning workspace',
'academic workflow automation',
'student success platform',
'ai exam preparation platform',
'smart revision platform',
'ai powered study dashboard',
'next gen student portal',
'virtual academic assistant',
'cloud learning management system',
'ai driven education software',
'smart university platform',
'digital academic infrastructure',
'automated academic planner',
'ai notes generator',
'ai powered note taking app',
'lecture summarizer ai',
'ai summary tool for students',
'academic content generator',
'ai research paper helper',
'ai citation generator',
'academic writing assistant ai',
'research workflow platform',
'college productivity software',
'student organization app',
'academic task automation tool',
'study management system',
'course tracking dashboard',
'subject progress tracker',
'academic goal tracking system',
'student habit tracker app',
'daily study planner online',
'college timetable generator',
'automatic schedule planner',
'campus productivity hub',
'academic collaboration platform',
'teacher student collaboration tool',
'digital classroom management system',
'ai powered grading assistant',
'assignment management system',
'smart homework tracker',
'academic crm system',
'education performance insights',
'student intelligence dashboard',
'learning behavior analytics',
'education data visualization platform',
'knowledge management for students',
'study optimization platform',
'learning acceleration platform',
'deep work study app',
'focus timer for students',
'pomodoro study app ai',
'distraction free study platform',
'academic break management tool',
'student mental focus app',
'skill based learning platform',
'competency tracking system',
'project based learning dashboard',
'higher education tech platform',
'college digital transformation platform',
'school digital ecosystem',
'universities ai platform',
'academic automation software',
'global edtech platform',
'education innovation hub',
'intelligent tutoring system',
'smart academic engine',
'academic ai infrastructure',
'learning intelligence system',
'student digital twin platform',
'future of education platform',
'ai powered academic suite',
'education productivity suite',
'unified learning environment',
'centralized academic dashboard',
'modern learning operating system',
  'ai tutor for indian students',
'online study platform india',
'best study app for college students india',
'ai homework helper india',
'exam preparation platform india',
'college study planner india',
'smart study planner for indian students',
'academic dashboard for students india',
'ai ppt generator india',
'presentation maker for college india',
'ai assignment solver india',
'research paper helper india',
'university study notes india',
'free study material for university exams india',
'engineering study platform india',
'bsc computer science study material india',
'mca entrance exam preparation platform',
'mca cet preparation app',
'gate exam study platform india',
'ugc net preparation platform',
'semester exam planner india',
'college timetable generator india',
'smart academic management system india',
'student productivity app india',
'academic performance tracker india',
'student analytics dashboard india',
'online practical preparation platform india',
'previous year question paper solution india',
'ai tutor for engineering students india',
'ethical hacking study material india',
'cloud computing notes india',
'data science study platform india',
'artificial intelligence notes india',
'software testing notes india',
'cyber security study material india',
'indian university digital platform',
'mumbai college study platform',
'maharashtra university exam preparation',
'ty bsc cs study material',
'indian competitive exam study app',
'smart revision app for indian students',
'education super app india',
'ai powered learning platform india',
'best ai study assistant india',
'online study dashboard india',
'digital campus platform india',
'student management system india',
'teacher lesson planner india',
'academic crm for colleges india',
'campus productivity app india',
'gamified learning platform india',
'multilingual dictionary for indian students',
'hindi english academic dictionary online',
'marathi english study dictionary',
'online learning management system india',
'edtech startup india platform',
'cloud based academic software india',
'academic automation software india',
'future of education india ai',
'smart university platform india',
  'ai academic operating system india',
'student operating system platform india',
'academic super app for indian students',
'intelligent campus dashboard india',
'unified academic workspace india',
'learning intelligence engine india',
'personalized semester command center',
'academic mission control platform',
'student productivity command hub',
'education workflow automation india',
'ai powered semester management system',
'digital scholar workspace india',
'smart academic cockpit india',
'future ready campus technology india',
'academic digital twin for students',
'self optimizing study platform india',
'learning performance intelligence india',
'ai driven exam acceleration system',
'next generation study ecosystem india',
'deep focus academic platform',
'education analytics intelligence india',
'autonomous learning assistant india',
'study optimization engine',
'college productivity operating system',
'student performance intelligence suite',
'academic growth tracking engine',
'smart syllabus execution platform',
'ai powered revision accelerator',
'academic efficiency platform india',
'education automation suite india',
'student success intelligence hub',
'intelligent timetable execution system',
'data driven academic mastery platform',
'personal academic command dashboard',
'holistic study management ecosystem',
'learning acceleration infrastructure india',
'education intelligence super app',
'modern scholar productivity suite',
'academic systems architecture platform',
'student knowledge operating system',
'ai powered campus transformation india',
  'studyspark',
'edtech',
'elearning',
'learntech',
'scholarly',
'academics',
'scholars',
'studyhub',
'learnhub',
'campus',
'classroom',
'tutoring',
'mentorship',
'syllabus',
'curriculum',
'assignments',
'examinations',
'semester',
'productivity',
'analytics',
'dashboard',
'workspace',
'planner',
'scheduler',
'generator',
'automation',
'intelligence',
'innovation',
'acceleration',
'optimization',
'mastery',
'knowledge',
'learning',
'education',
'academia',
'research',
'notetaking',
'summarizer',
'presentation',
'dictionary',
'multilingual',
'gamification',
'collaboration',
'cloud',
'saas',
'digital',
'platform',
'ecosystem',
'infrastructure',
'transformation',
'future',
'focus',
'efficiency',
'performance',
'insights',
'progress',
'tracking',
'workflow',
'system',
'engine',
'command',
'hub',
'suite',
'portal',
'mentor',
'scholar',
'students',
'teachers',
'universities',
'campustechnology',
'studytech',
'academify',
'learnify',
'studion',
'educore',
'learnova',
'scholaro',
'acadexa',
'intellilearn'
  ],
  authors: [{ name: 'Rishabdev Tripathi' }],
  creator: 'Rishabdev Tripathi',
  publisher: 'StudySpark',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎓</text></svg>" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
      </head>
      <body className="font-sans antialiased selection:bg-primary/10">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <FirebaseErrorListener />
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
